In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
data = pd.read_csv('data_2.csv')

In [37]:
print(data_1.shape)

(9564, 141)

In [38]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Columns: 141 entries, rowid to koi_dikco_msky_err
dtypes: float64(118), int64(7), object(16)
memory usage: 10.3+ MB
None

In [39]:
#for more clarity renaming the columns that we need
data = data.rename(columns={'kepid':'KepID',
'kepoi_name':'KOIName',
'kepler_name':'KeplerName',
'koi_disposition':'ExoplanetArchiveDisposition',
'koi_pdisposition':'DispositionUsingKeplerData',
'koi_score':'DispositionScore',
'koi_fpflag_nt':'NotTransit-LikeFalsePositiveFlag',
'koi_fpflag_ss':'koi_fpflag_ss',
'koi_fpflag_co':'CentroidOffsetFalsePositiveFlag',
'koi_fpflag_ec':'EphemerisMatchIndicatesContaminationFalsePositiveFlag',
'koi_period':'OrbitalPeriod',
'koi_period_err1':'OrbitalPeriodUpperUnc',
'koi_period_err2':'OrbitalPeriodLowerUnc',
'koi_time0bk':'TransitEpoch',
'koi_time0bk_err1':'TransitEpochUpperUnc',
'koi_time0bk_err2':'TransitEpochLowerUnc',
'koi_impact':'ImpactParamete',
'koi_impact_err1':'ImpactParameterUpperUnc',
'koi_impact_err2':'ImpactParameterLowerUnc',
'koi_duration':'TransitDuration',
'koi_duration_err1':'TransitDurationUpperUnc',
'koi_duration_err2':'TransitDurationLowerUnc',
'koi_depth':'TransitDepth',
'koi_depth_err1':'TransitDepthUpperUnc',
'koi_depth_err2':'TransitDepthLowerUnc',
'koi_prad':'PlanetaryRadius',
'koi_prad_err1':'PlanetaryRadiusUpperUnc',
'koi_prad_err2':'PlanetaryRadiusLowerUnc',
'koi_teq':'EquilibriumTemperature',
'koi_teq_err1':'EquilibriumTemperatureUpperUnc',
'koi_teq_err2':'EquilibriumTemperatureLowerUnc',
'koi_insol':'InsolationFlux',
'koi_insol_err1':'InsolationFluxUpperUnc',
'koi_insol_err2':'InsolationFluxLowerUnc',
'koi_model_snr':'TransitSignal-to-Nois',
'koi_tce_plnt_num':'TCEPlanetNumbe',
'koi_tce_delivname':'TCEDeliver',
'koi_steff':'StellarEffectiveTemperature',
'koi_steff_err1':'StellarEffectiveTemperatureUpperUnc',
'koi_steff_err2':'StellarEffectiveTemperatureLowerUnc',
'koi_slogg':'StellarSurfaceGravity',
'koi_slogg_err1':'StellarSurfaceGravityUpperUnc',
'koi_slogg_err2':'StellarSurfaceGravityLowerUnc',
'koi_srad':'StellarRadius',
'koi_srad_err1':'StellarRadiusUpperUnc',
'koi_srad_err2':'StellarRadiusLowerUnc',
'ra':'RA',
'dec':'Dec',
'koi_kepmag':'Kepler-band'
})

In [41]:
data.head()

,rowid,KepID,KOIName,KeplerName,ExoplanetArchiveDisposition,koi_vet_stat,koi_vet_date,DispositionUsingKeplerData,DispositionScore,NotTransit-LikeFalsePositiveFlag,...,koi_dicco_mdec,koi_dicco_mdec_err,koi_dicco_msky,koi_dicco_msky_err,koi_dikco_mra,koi_dikco_mra_err,koi_dikco_mdec,koi_dikco_mdec_err,koi_dikco_msky,koi_dikco_msky_err
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,Done,16-08-2018,CANDIDATE,1.000,0,...,0.200,0.160,0.200,0.170,0.080,0.130,0.310,0.170,0.320,0.160
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,Done,16-08-2018,CANDIDATE,0.969,0,...,0.000,0.480,0.390,0.360,0.490,0.340,0.120,0.730,0.500,0.450
2,3,10811496,K00753.01,NaN,CANDIDATE,Done,16-08-2018,CANDIDATE,0.000,0,...,-0.034,0.070,0.042,0.072,0.002,0.071,-0.027,0.074,0.027,0.074
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,Done,16-08-2018,FALSE POSITIVE,0.000,0,...,0.147,0.078,0.289,0.079,-0.257,0.072,0.099,0.077,0.276,0.076
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,Done,16-08-2018,CANDIDATE,1.000,0,...,-0.090,0.180,0.100,0.140,0.070,0.180,0.020,0.160,0.070,0.200

In [44]:
selected = data
print(selected.shape)
selected = selected.loc[:,selected.columns.intersection(['DispositionScore','OrbitalPeriod','OrbitalPeriodUpperUnc','OrbitalPeriodLowerUnc','TransitEpoch','TransitEpochUpperUnc',
                                                        'TransitEpochLowerUnc','ImpactParamete','ImpactParameterUpper',])]
print(selected.shape)
selected.head()

(9564, 141)
(9564, 6)

,DispositionScore,OrbitalPeriod,OrbitalPeriodUpperUnc,OrbitalPeriodLowerUnc,TransitEpoch,TransitEpochUpperUnc
0,1.000,9.488036,2.780000e-05,-2.780000e-05,170.538750,0.002160
1,0.969,54.418383,2.480000e-04,-2.480000e-04,162.513840,0.003520
2,0.000,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581
3,0.000,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115
4,1.000,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130